### ISSUE TITLE
Working with multiple components per entity?

### ISSUE THREAD

**Issue by MrRhodes** [ddmills/geotic#2]
This may be against ECS principles, but have you considered the possibility of multiples of the same components on an entity?

For example, an entity with multiple "collision" shapes....

**Comment by ddmills** [comment]
I have absolutely ran into this issue. When originally putting this together, I hadn't considered allowing multiple of the same type. Having multiples of the same type of component would certainly muddy up the interface. What would a decent high-level interface look like?

I was usually able to solve it by doing something like, having a `collision` component which can have a list of shapes.

**Comment by ddmills** [comment]
this is in v3

**Comment by MrRhodes** [comment]
Wow.... still in dev!
