### ISSUE TITLE
Query isTracking issue

### ISSUE THREAD

**Issue by lagdotcom** [ddmills/geotic#38]
https://github.com/ddmills/geotic/blob/a0a66a65fd64926427fc07b909734f81e8753bca/src/Query.js#L60

Shouldn't this read `if (!isTracking && ...`? There's no isTracking field on the Query.

**Comment by ddmills** [comment]
good catch!!

**Comment by ddmills** [comment]
@lagdotcom this is fixed in v4.1.6
