### ISSUE TITLE
Issues with serialization

### ISSUE THREAD

**Issue by jdrew1303** [ddmills/geotic#4]
Hey 👋 

First off, thanks for the great library. It's been my gateway into ECS and writing games. 👍 

Serialisation of entities is currently broken. [The issue is on line 92:](https://github.com/ddmills/geotic/blob/master/source/geotic.js#L92) 

```javascript
tags: Object.keys(this.t),
```

should be 

```javascript
tags: Object.keys(this.tags),
```

I'd be happy to put in a PR for this?

**Comment by ddmills** [comment]
@jdrew1303 if you find time to make a PR I can get that merged in and bump the library version 🚀

**Comment by jdrew1303** [comment]
Ok. I've a PR in and it should be good to go 👍 If there's any issues just let me know. 

If I come across any other bits I'll put some PR's together for them. Thanks again for the library.

**Comment by ddmills** [comment]
This is in `2.4.3`, thank you for contributing!
