### ISSUE TITLE
onDetached doesn't seem to trigger

### ISSUE THREAD

**Issue by dcazrael** [ddmills/geotic#41]
I was trying to remove an entry from a cache set when removing the position of an entity like this.
The onDestroy method is triggered properly when the entity is destroyed however, I wasn't able to trigger the onDetached method.

When checking in the code, I couldn't find the method anymore.

```js
onPickUp(evt) {
    this.inventoryItemIds.push(evt.data.id);

    if (evt.data.position) {
      evt.data.remove(evt.data.position);
      evt.data.remove(evt.data.isPickup);
    }
  }
```

```js
export class Position extends Component {
  static properties = { x: 0, y: 0 };
  onAttached() {
    const locId = `${this.entity.position.x},${this.entity.position.y}`;

    addCacheSet('entitiesAtLocation', locId, this.entity.id);
  }

  onDetached() {
    const locId = `${this.x},${this.y}`;
    deleteCacheSet('entitiesAtLocation', locId, this.entity.id);
  }

  onDestroyed() {
    const locId = `${this.x},${this.y}`;
    deleteCacheSet('entitiesAtLocation', locId, this.entity.id);
  }
}
```

**Comment by ddmills** [comment]
ah good catch @dcazrael. The `onDetached` method has been removed, as there is no longer a "detached" state for components. Instead, it should just be using `onDestroyed`
