### ISSUE TITLE
static property contentIds on Inventory component is a reference across entities

### ISSUE THREAD

**Issue by luetkemj** [ddmills/geotic#57]
This is another weird one but I don't see anywhere in my codebase where I am explicitly assigning the property in a way that would create a reference so I figured I'd submit a bug report. For context, I based the Inventory, Loot, and take/drop eventing on your game sleepy.

### Actual Behavior
I have two actors in my game, the player and a goblin. They both start with an empty Inventory. If either actor adds an item to their Inventory, it will appear in the contentIds array for both actors.

### Expected Behavior
Inventory contentIds should not be shared across entities.

### Repro
Clone and install this [branch](https://github.com/luetkemj/skrimshank/tree/inventory-reference-bug-repro).

Open the console in dev tools. Using your mouse, click on the `@` and `g` to log all entities at both locations to the console. Inspect the `@` and `g` entities to confirm that they both have an Inventory component and that inventory.contentIds array is empty.

Use the arrow keys to navigate to a lockpick `~` press the `i` key when adjacent to the lockpick to activate the interactions menu. Use the `a` key to pick up the lockpick.

Using your mouse, click on the `@` and `g` to again log all entities at both locations to the console. Inspect the `@` and `g` to confirm that they both have an Inventory component and that inventory.contentIds contains the same id.

Furthermore you can test that they are a reference with the following script in the console (wrld is a global reference to the current world object)

`wrld.getEntity(<playerEntityId>).inventory.contentIds == wrld.getEntity(<goblinEntityId>).inventory.contentIds` // returns true

**Comment by luetkemj** [comment]
### Followup
If I assign contentIds to an array in the onAttatched hook - they do not share a reference. 

```
onAttached() {
    this.contentIds = [];
}
```

I'm wondering if this might be an issue with array type properties in general - I don't think I really have any others in my game yet that would have been tested in the way.

**Comment by ddmills** [comment]
Thank you @luetkemj, I was able to clone and reproduce the issue.

This is an issue with non-primitive component properties. I don't see an easy fix for this. Previously, I had a special type `<EntityArray>` which would handle all entity list tracking and garbage collection automatically. This went away when the library moved to bitsets.

The workaround you have is good, but I don't know how it'll interact with serialization.


I wonder if it makes sense to explicitly [detect the type in the component constructor](https://github.com/ddmills/geotic/blob/master/src/Component.js#L18), and shallow-clone any arrays. Additionally, we could throw an error or warning if the property type is not primitive.


I think we could make a simple failing unit test to cover this particular scenario.

**Comment by ddmills** [comment]
see #42 and #39

**Comment by ddmills** [comment]
Another potential solution would be to `JSON.stringify()` and `JSON.parse()` the properties on component construction. This would put a requirement on properties, albeit I think one that would enforce better practice. This would also ensure serialization works across all components.

**Comment by ddmills** [comment]
@luetkemj this should be fixed in `geotic@4.3.0`
