### ISSUE TITLE
How to remove components that support multiples?

### ISSUE THREAD

**Issue by luetkemj** [ddmills/geotic#9]
I was trying to allow for adding multiple Animate components on an entity. For example: to mix a color and shake animation.

Trying to remove a completed animation component here: https://github.com/luetkemj/snail6/blob/9488e37799517368850b7a3aa10f4008b6631138/src/systems/animation.js#L20 

Getting the following error: 
`Uncaught TypeError: _component._onDetached is not a function`

I tried passing in the component itself like this: 

` return entity.remove(animationX);`

And get the same error.

Geotic has been pretty solid so far so it's probably user error. The only complaint I really have is some of the docs are a bit out of date so I've had to inspect the code to get some methods right. Not a huge deal. Great work!

**Comment by ddmills** [comment]
hmm, remove by `instance` *should* be working, i have a little test for it here: https://github.com/ddmills/geotic/blob/master/tests/unit/Entity.spec.js#L252

In your scenario, it looks like the `Animate` component has `allowMultiple` as a component property, when it should be a static property on the class itself.

from [src/components/Animate.js](https://github.com/luetkemj/snail6/blob/9488e37799517368850b7a3aa10f4008b6631138/src/components/Animate.js#L6)

```js
import { colors } from "../lib/graphics";
import { Component } from "geotic";

export default class Animate extends Component {
  static allowMultiple = true; // should be a static property on the class
  static properties = {
    ...
  };
}
```

**Comment by ddmills** [comment]
if you have a handle on `component`, you can call `.remove()` on it as well:
```js
const component = entity.animate[0];

component.destroy();
```

**Comment by luetkemj** [comment]
I updated this branch https://github.com/luetkemj/snail6/tree/animate-shake with your suggestions and a simplified error case. Maybe you'll see the problem if you run that branch?

npm i
npm start

then just find a goblin (g) and bump into it with your developer tools open.

**Comment by luetkemj** [comment]
> static allowMultiple = true; // should be a static property on the class

That was it! Don't forget to make allowMultiple static :)

Thanks for the help
